site_name: NSPS Connector Implementation Guide
site_url: https://wiki.portaone.com/display/REQSPEC/NSPS+Connector+Implementation+Guide
nav:
    - get-started.md
    - Introduction: index.md
    - mcp-instruction.md
    - connector-overview.md
    - NSPS:
          - NSPS/nsps-overview.md
          - NSPS/data-flows.md
          - NSPS/technical-specifications.md
    - Implementation Specific:
          - implementation-specific/requirements.md
          - Request Handling:
                - implementation-specific/request-handling/request-body.md
                - implementation-specific/request-handling/request-headers.md
                - implementation-specific/request-handling/event-types.md
          - implementation-specific/configuration.md
          - implementation-specific/logging.md
          - implementation-specific/error-handling.md
          - implementation-specific/best-practices.md
    - deployment.md
    - testing.md
    - Examples:
          - Python:
                - WTL HLR HSS Connector: examples/python/wtl-hlr-hss-connector/overview.md
                - Simple Connector FastAPI: examples/python/simple-connector-fastapi/overview.md
          - TypeScript:
                - Simple Connector Express: examples/typescript/simple-connector-express/overview.md
watch:
    - docs
    - includes

plugins:
    - offline

theme:
    name: material
    logo: assets/images/portaone-main-logo.png
    favicon: assets/images/favicon.ico
    features:
        - content.code.copy
        - navigation.footer
    font:
        text: Roboto
        code: Red Hat Mono
    palette:
        #Dark mode
        - scheme: slate
          toggle:
              icon: material/weather-sunny
              name: Dark mode
          primary: blue
          accent: blue

        #Light mode
        - scheme: default
          toggle:
              icon: material/weather-night
              name: Light mode
          primary: blue
          accent: blue

markdown_extensions:
    - admonition
    - attr_list
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - tables
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets:
          auto_append:
              - includes/abbreviations.md
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.details
    - md_in_html
    - abbr
    - def_list

extra_css:
    - stylesheets/extra.css

copyright: Copyright &copy; 2025 PortaOne, Inc. All rights reserved.
