name: ci
on:
    push:
        branches:
            - master
            - main
permissions:
    contents: write
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Configure Git Credentials
              run: |
                  git config user.name github-actions[bot]
                  git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            - uses: actions/setup-python@v5
              with:
                  python-version: 3.x
            - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
            - uses: actions/cache@v4
              with:
                  key: mkdocs-material-${{ env.cache_id }}
                  path: .cache
                  restore-keys: |
                      mkdocs-material-
            - run: pip install -r requirements.txt
            - run: mkdocs build
            - run: mkdocs gh-deploy --force
            - run:  |
                cd site
                git init
                git remote add origin https://github.com/username/repo.git
                git fetch origin gh-pages
                git checkout gh-pages
                python ../copy_md.py
                git add md/
                git commit -m "Add raw md files"
                git push -f origin gh-pages