name: ci
on:
    push:
        branches:
            - master
            - main
permissions:
    contents: write
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Configure Git Credentials
              run: |
                  git config user.name github-actions[bot]
                  git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            - uses: actions/setup-python@v5
              with:
                  python-version: 3.x
            - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
            - uses: actions/cache@v4
              with:
                  key: mkdocs-material-${{ env.cache_id }}
                  path: .cache
                  restore-keys: |
                      mkdocs-material-
            - run: pip install -r requirements.txt
            - run: mkdocs build
            - run: mkdocs gh-deploy --force
            - name: Clone gh-pages branch (temp)
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  git clone --depth 1 --branch gh-pages https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} gh-pages-temp

            - name: Copy raw .md into gh-pages clone
              run: |
                  python copy_md_to_ghpages.py gh-pages-temp

            - name: Commit & push raw .md to gh-pages (if changed)
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  cd gh-pages-temp
                  git config user.name "github-actions[bot]"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git add md || true
                  # Also add md/llms.txt if present
                  git add md/llms.txt || true
                  # if nothing staged, exit quietly
                  if git diff --cached --quiet; then
                      echo "No raw markdown changes to push"
                  else
                      git commit -m "Add/Update raw md files"
                      git push origin gh-pages
                  fi
